site_name: Dataflow
theme:
  logo: assets/Color_Dataflow_vec.svg
  favicon: assets/Color_Dataflow_vec.svg
  palette: 
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/weather-night
        name: Switch to light mode
  name: material
  features:
    - navigation.tabs
    - navigation.expand
    - navigation.top
    - navigation.sections
    - navigation.instant
    - navigation.tracking
    - navigation.search.highlight
    - navigation.search.share
    - navigation.search.suggest
    - navigation.search.suggest.highlight
    - navigation.search.suggest.share
    - navigation.search.suggest.tracking
    - search.highlight
    - search.share
    - search.suggest
    - search.suggest.highlight
    - search.suggest.share
    - search.suggest.tracking
nav:
  - About:
    - ğŸ‘‹ Welcome: index.md
    - â“ Why Dataflow: about/why-dataflow.md
    - ğŸ’¡ Use Cases: about/use-cases.md
    - âœ¨ Features: about/features.md
    - ğŸ‘¨â€ğŸ’» Developer: about/developer.md
    - ğŸ“œ EULA: about/EULA.md
  - Documentation:
    - ğŸš€ Getting Started: documentation/getting-started.md
    - ğŸ› ï¸ Using Dataflow: documentation/using-dataflow.md
    - ğŸ“¡ Google Sheets API Setup: documentation/google-api.md
    - ğŸ”— Data Sources: documentation/data-sources.md
    - ğŸ¤– Agent: documentation/agent.md
    - ğŸ“› Troubleshooting: documentation/troubleshooting.md
  - Tutorials: tutorials/tutorials.md
  - FAQ: faq/faq.md
  - Downloads: downloads/downloads.md
extra:
  generator: false
  social:
    - icon: simple/github
      link: https://github.com/fledermoys
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/max-gr%C3%BCnwald-437692225/
    - icon: simple/x
      link: https://twitter.com/fledermoys
    - icon: fontawesome/brands/behance
      link: https://www.behance.net/maxgr

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  - attr_list
  - md_in_html
  - pymdownx.blocks.caption
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - def_list

copyright:
  Â© 2025 <a href="https://www.linkedin.com/in/max-gr%C3%BCnwald-437692225/" tarfget="_blank" rel="noopener">Max GrÃ¼nwald</a>
extra_css:
- stylesheets/extra.css